spring:
  application:
    name: OversizedTrashTokyo
  config:
    import: 
      - classpath:input-value.yml
      - classpath:mail.yml

url:
  page:
    top: https://sodai.tokyokankyo.or.jp/Sodai/V2Index/0/0/0/0/
